# Generated by Django 6.0.1 on 2026-01-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
