# Generated by Django 6.0.1 on 2026-01-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
